/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** References */
        get: operations["references_api_references_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenarios */
        get: operations["scenarios_api_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute */
        post: operations["compute_api_compute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Caveat
         * @description External validity / sanity caveat entry (SPEC §4.4).
         */
        Caveat: {
            /** Id */
            id: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "critical";
            /** Message */
            message: string;
        };
        /**
         * CoefficientRecord
         * @description The coefficient used for the compute call (plus citation).
         */
        CoefficientRecord: {
            /** Source Id */
            source_id: string;
            /** Label */
            label: string;
            /** Beta */
            beta: number;
            /** Std Err */
            std_err: number;
            /** Region */
            region: string;
            /** Sector */
            sector: string;
            /** Citation */
            citation: string;
            /** Url */
            url?: string | null;
        };
        /**
         * ComputeRequest
         * @description POST /api/compute body — currently a thin wrapper around ScenarioInputs.
         */
        ComputeRequest: {
            inputs: components["schemas"]["ScenarioInputs"];
        };
        /**
         * ComputeResponse
         * @description POST /api/compute response.
         *
         *     `method` is pinned to "reduced_form" in V1 so V2 can add "mac_curve"
         *     without breaking the contract (§4.5).
         */
        ComputeResponse: {
            /**
             * Method
             * @default reduced_form
             * @constant
             */
            method: "reduced_form";
            /** Years */
            years: number[];
            /** Bau Mt */
            bau_mt: number[];
            /** Deterministic Mt */
            deterministic_mt: number[];
            percentiles_mt: components["schemas"]["PercentileBands"] | null;
            kpis: components["schemas"]["KPIBundle"];
            /** Caveats */
            caveats: components["schemas"]["Caveat"][];
            coefficient: components["schemas"]["CoefficientRecord"];
            /** Mc N Effective */
            mc_n_effective: number;
            /** Mc Seed */
            mc_seed: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * KPIBundle
         * @description Headline metrics surfaced in the UI card row.
         */
        KPIBundle: {
            /** Cumulative Reduction Mt Median */
            cumulative_reduction_mt_median: number;
            /** Cumulative Reduction Mt P5 */
            cumulative_reduction_mt_p5: number;
            /** Cumulative Reduction Mt P95 */
            cumulative_reduction_mt_p95: number;
            /** Peak Year Median */
            peak_year_median: number;
            /** Peak Year P5 */
            peak_year_p5: number;
            /** Peak Year P95 */
            peak_year_p95: number;
            /** Emissions 2035 Mt Median */
            emissions_2035_mt_median: number;
            /** Relative Reduction 2035 Median */
            relative_reduction_2035_median: number;
        };
        /** PercentileBands */
        PercentileBands: {
            /** P5 */
            p5: number[];
            /** P25 */
            p25: number[];
            /** P50 */
            p50: number[];
            /** P75 */
            p75: number[];
            /** P95 */
            p95: number[];
        };
        /**
         * PricePoint
         * @description Single year/price pair in a price path.
         */
        PricePoint: {
            /** Year */
            year: number;
            /**
             * Price Cny
             * @description Carbon price CNY/tCO2
             */
            price_cny: number;
        };
        /**
         * ReferenceEntry
         * @description Literature coefficient alternate served from references.db.
         */
        ReferenceEntry: {
            /** Id */
            id: string;
            /** Citation */
            citation: string;
            /** Region */
            region: string;
            /** Sector */
            sector: string;
            /** Coefficient */
            coefficient: number;
            /** Std Err */
            std_err: number;
            /** Method */
            method: string;
            /** Notes */
            notes?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * ScenarioInputs
         * @description User inputs per SPEC §8.2.
         *
         *     Field ranges match the sliders declared in SPEC §4.1. `mc_n = 0` disables
         *     Monte Carlo per SPEC §4.3 and is the canonical determinism gate
         *     (§9 criterion 2).
         */
        ScenarioInputs: {
            /** Price Path */
            price_path: components["schemas"]["PricePoint"][];
            /**
             * Free Allocation Share
             * @default 0.9
             */
            free_allocation_share: number;
            /**
             * Coefficient Source
             * @default author_did_2026
             */
            coefficient_source: string;
            /**
             * Alpha
             * @default 0.3
             */
            alpha: number;
            /**
             * Gdp Growth
             * @default 0.045
             */
            gdp_growth: number;
            /**
             * Energy Intensity Improvement
             * @default 0.02
             */
            energy_intensity_improvement: number;
            /**
             * Electrification Rate
             * @default 0.005
             */
            electrification_rate: number;
            /**
             * Mc N
             * @default 10000
             */
            mc_n: number;
            /**
             * Mc Seed
             * @default 42
             */
            mc_seed: number;
            /**
             * E 2020 Mt
             * @default 5150
             */
            e_2020_mt: number;
        };
        /**
         * ScenarioPreset
         * @description A curated preset served from scenarios.db.
         */
        ScenarioPreset: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            inputs: components["schemas"]["ScenarioInputs"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    references_api_references_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceEntry"][];
                };
            };
        };
    };
    scenarios_api_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioPreset"][];
                };
            };
        };
    };
    compute_api_compute_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComputeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComputeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
